name: C Program CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install build dependencies (GCC)
      - name: Set up GCC
        run: sudo apt-get install -y build-essential

      # Step 3: Compile the C program
      - name: Compile C program
        run: gcc parking.cpp -o parking_system

      # Step 4: Run the compiled program
      - name: Run C program
        run: ./parking

      # Step 5: Upload the build artifacts (optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-program
          path: ./parking
